[project]
name = "zalo-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl==3.1.2",
    "pyautogui>=0.9.54",
    "selenium==4.10.0",
    "streamlit>=1.45.1",
]
